///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_integration_consume_setting

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *UmsIntegrationConsumeSetting {
	return new(UmsIntegrationConsumeSetting)
}

func NewQueryBuilder() *umsIntegrationConsumeSettingQueryBuilder {
	return new(umsIntegrationConsumeSettingQueryBuilder)
}

func (t *UmsIntegrationConsumeSetting) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsIntegrationConsumeSettingQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&UmsIntegrationConsumeSetting{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Update(db *gorm.DB, data *UmsIntegrationConsumeSetting) (cnt int64, err error) {
	db = db.Model(&UmsIntegrationConsumeSetting{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(data)
	err = ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "update err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&UmsIntegrationConsumeSetting{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsIntegrationConsumeSetting{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) First(db *gorm.DB) (*UmsIntegrationConsumeSetting, error) {
	ret := &UmsIntegrationConsumeSetting{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) QueryOne(db *gorm.DB) (*UmsIntegrationConsumeSetting, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsIntegrationConsumeSetting, error) {
	var ret []*UmsIntegrationConsumeSetting
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Limit(limit int) *umsIntegrationConsumeSettingQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) Offset(offset int) *umsIntegrationConsumeSettingQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereIdIn(value []int64) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereIdNotIn(value []int64) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) OrderById(asc bool) *umsIntegrationConsumeSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereDeductionPerAmount(p mysql.Predicate, value int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deduction_per_amount", p),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereDeductionPerAmountIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deduction_per_amount", "IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereDeductionPerAmountNotIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "deduction_per_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) OrderByDeductionPerAmount(asc bool) *umsIntegrationConsumeSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "deduction_per_amount "+order)
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereMaxPercentPerOrder(p mysql.Predicate, value int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_percent_per_order", p),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereMaxPercentPerOrderIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_percent_per_order", "IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereMaxPercentPerOrderNotIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_percent_per_order", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) OrderByMaxPercentPerOrder(asc bool) *umsIntegrationConsumeSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "max_percent_per_order "+order)
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereUseUnit(p mysql.Predicate, value int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "use_unit", p),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereUseUnitIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "use_unit", "IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereUseUnitNotIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "use_unit", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) OrderByUseUnit(asc bool) *umsIntegrationConsumeSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "use_unit "+order)
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereCouponStatus(p mysql.Predicate, value int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "coupon_status", p),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereCouponStatusIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "coupon_status", "IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) WhereCouponStatusNotIn(value []int32) *umsIntegrationConsumeSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "coupon_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsIntegrationConsumeSettingQueryBuilder) OrderByCouponStatus(asc bool) *umsIntegrationConsumeSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "coupon_status "+order)
	return qb
}
