FROM golang:1.22.3 AS builder

WORKDIR /work
ENV GOPROXY=https://goproxy.cn,direct
COPY . .
RUN go build -o bin/admin cmd/mall_admin/main.go

FROM alpine:3.17
WORKDIR /work
COPY --from=builder /work/bin/. .
COPY --from=builder /work/configs  ./configs

RUN set -eux; \  
    # 替换源
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories; \
    # 解决时区问题
    apk add --no-cache tzdata; \
    ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
    # 二进制文件无法通过./执行 ; \
    apk add --no-cache libc6-compat; \
    # 在go程序中无法访问https链接; \
    apk add --no-cache ca-certificates

EXPOSE 8080/tcp
CMD ["./admin", "-env", "pro"]