///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_permission

import (
	"fmt"
	"time"

	"github.com/pkg/errors"
	"gorm.io/gorm"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"
)

func NewModel() *UmsPermission {
	return new(UmsPermission)
}

func NewQueryBuilder() *umsPermissionQueryBuilder {
	return new(umsPermissionQueryBuilder)
}

func (t *UmsPermission) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsPermissionQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsPermissionQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsPermissionQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&UmsPermission{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsPermissionQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&UmsPermission{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsPermissionQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsPermission{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, nil
	}
	return c, res.Error
}

func (qb *umsPermissionQueryBuilder) First(db *gorm.DB) (*UmsPermission, error) {
	ret := &UmsPermission{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, nil
	}
	return ret, res.Error
}

func (qb *umsPermissionQueryBuilder) QueryOne(db *gorm.DB) (*UmsPermission, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsPermissionQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsPermission, error) {
	var ret []*UmsPermission
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsPermissionQueryBuilder) Limit(limit int) *umsPermissionQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsPermissionQueryBuilder) Offset(offset int) *umsPermissionQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereIdIn(value []int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereIdNotIn(value []int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderById(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WherePid(p mysql.Predicate, value int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pid", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WherePidIn(value []int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pid", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WherePidNotIn(value []int64) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pid", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByPid(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "pid "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereName(p mysql.Predicate, value string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereNameIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereNameNotIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByName(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereValue(p mysql.Predicate, value string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "value", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereValueIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "value", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereValueNotIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "value", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByValue(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "value "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereIcon(p mysql.Predicate, value string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereIconIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereIconNotIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByIcon(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "icon "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereType(p mysql.Predicate, value int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereTypeIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereTypeNotIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByType(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereUri(p mysql.Predicate, value string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uri", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereUriIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uri", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereUriNotIn(value []string) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "uri", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByUri(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "uri "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereStatusIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereStatusNotIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByStatus(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereCreateTime(p mysql.Predicate, value time.Time) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereCreateTimeIn(value []time.Time) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereCreateTimeNotIn(value []time.Time) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderByCreateTime(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_time "+order)
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereSort(p mysql.Predicate, value int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", p),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereSortIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) WhereSortNotIn(value []int32) *umsPermissionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsPermissionQueryBuilder) OrderBySort(asc bool) *umsPermissionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sort "+order)
	return qb
}
