///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package oms_order_return_reason

import (
	"fmt"
	"time"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *OmsOrderReturnReason {
	return new(OmsOrderReturnReason)
}

func NewQueryBuilder() *omsOrderReturnReasonQueryBuilder {
	return new(omsOrderReturnReasonQueryBuilder)
}

func (t *OmsOrderReturnReason) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type omsOrderReturnReasonQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *omsOrderReturnReasonQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *omsOrderReturnReasonQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&OmsOrderReturnReason{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *omsOrderReturnReasonQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&OmsOrderReturnReason{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *omsOrderReturnReasonQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&OmsOrderReturnReason{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, nil
	}
	return c, res.Error
}

func (qb *omsOrderReturnReasonQueryBuilder) First(db *gorm.DB) (*OmsOrderReturnReason, error) {
	ret := &OmsOrderReturnReason{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, nil
	}
	return ret, res.Error
}

func (qb *omsOrderReturnReasonQueryBuilder) QueryOne(db *gorm.DB) (*OmsOrderReturnReason, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *omsOrderReturnReasonQueryBuilder) QueryAll(db *gorm.DB) ([]*OmsOrderReturnReason, error) {
	var ret []*OmsOrderReturnReason
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *omsOrderReturnReasonQueryBuilder) Limit(limit int) *omsOrderReturnReasonQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) Offset(offset int) *omsOrderReturnReasonQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereId(p mysql.Predicate, value int64) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereIdIn(value []int64) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereIdNotIn(value []int64) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) OrderById(asc bool) *omsOrderReturnReasonQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereName(p mysql.Predicate, value string) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereNameIn(value []string) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereNameNotIn(value []string) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) OrderByName(asc bool) *omsOrderReturnReasonQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereSort(p mysql.Predicate, value int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", p),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereSortIn(value []int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereSortNotIn(value []int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "NOT IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) OrderBySort(asc bool) *omsOrderReturnReasonQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sort "+order)
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereStatusIn(value []int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereStatusNotIn(value []int32) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) OrderByStatus(asc bool) *omsOrderReturnReasonQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereCreateTime(p mysql.Predicate, value time.Time) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", p),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereCreateTimeIn(value []time.Time) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) WhereCreateTimeNotIn(value []time.Time) *omsOrderReturnReasonQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *omsOrderReturnReasonQueryBuilder) OrderByCreateTime(asc bool) *omsOrderReturnReasonQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_time "+order)
	return qb
}
