///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package pms_album_pic

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *PmsAlbumPic {
	return new(PmsAlbumPic)
}

func NewQueryBuilder() *pmsAlbumPicQueryBuilder {
	return new(pmsAlbumPicQueryBuilder)
}

func (t *PmsAlbumPic) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type pmsAlbumPicQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *pmsAlbumPicQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *pmsAlbumPicQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&PmsAlbumPic{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *pmsAlbumPicQueryBuilder) Update(db *gorm.DB, data *PmsAlbumPic) (cnt int64, err error) {
	db = db.Model(&PmsAlbumPic{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(data)
	err = ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "update err")
	}
	return ret.RowsAffected, nil
}

func (qb *pmsAlbumPicQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&PmsAlbumPic{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *pmsAlbumPicQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&PmsAlbumPic{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *pmsAlbumPicQueryBuilder) First(db *gorm.DB) (*PmsAlbumPic, error) {
	ret := &PmsAlbumPic{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *pmsAlbumPicQueryBuilder) QueryOne(db *gorm.DB) (*PmsAlbumPic, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *pmsAlbumPicQueryBuilder) QueryAll(db *gorm.DB) ([]*PmsAlbumPic, error) {
	var ret []*PmsAlbumPic
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *pmsAlbumPicQueryBuilder) Limit(limit int) *pmsAlbumPicQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) Offset(offset int) *pmsAlbumPicQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereId(p mysql.Predicate, value int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereIdIn(value []int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereIdNotIn(value []int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) OrderById(asc bool) *pmsAlbumPicQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereAlbumId(p mysql.Predicate, value int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "album_id", p),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereAlbumIdIn(value []int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "album_id", "IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WhereAlbumIdNotIn(value []int64) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "album_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) OrderByAlbumId(asc bool) *pmsAlbumPicQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "album_id "+order)
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WherePic(p mysql.Predicate, value string) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pic", p),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WherePicIn(value []string) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pic", "IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) WherePicNotIn(value []string) *pmsAlbumPicQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "pic", "NOT IN"),
		value,
	})
	return qb
}

func (qb *pmsAlbumPicQueryBuilder) OrderByPic(asc bool) *pmsAlbumPicQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "pic "+order)
	return qb
}
