///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_role_menu_relation

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *UmsRoleMenuRelation {
	return new(UmsRoleMenuRelation)
}

func NewQueryBuilder() *umsRoleMenuRelationQueryBuilder {
	return new(umsRoleMenuRelationQueryBuilder)
}

func (t *UmsRoleMenuRelation) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsRoleMenuRelationQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsRoleMenuRelationQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsRoleMenuRelationQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&UmsRoleMenuRelation{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *umsRoleMenuRelationQueryBuilder) Update(db *gorm.DB, data *UmsRoleMenuRelation) (cnt int64, err error) {
	db = db.Model(&UmsRoleMenuRelation{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(data)
	err = ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "update err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsRoleMenuRelationQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&UmsRoleMenuRelation{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *umsRoleMenuRelationQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsRoleMenuRelation{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *umsRoleMenuRelationQueryBuilder) First(db *gorm.DB) (*UmsRoleMenuRelation, error) {
	ret := &UmsRoleMenuRelation{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *umsRoleMenuRelationQueryBuilder) QueryOne(db *gorm.DB) (*UmsRoleMenuRelation, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsRoleMenuRelationQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsRoleMenuRelation, error) {
	var ret []*UmsRoleMenuRelation
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsRoleMenuRelationQueryBuilder) Limit(limit int) *umsRoleMenuRelationQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) Offset(offset int) *umsRoleMenuRelationQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereIdIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereIdNotIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) OrderById(asc bool) *umsRoleMenuRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereRoleId(p mysql.Predicate, value int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "role_id", p),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereRoleIdIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "role_id", "IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereRoleIdNotIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "role_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) OrderByRoleId(asc bool) *umsRoleMenuRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "role_id "+order)
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereMenuId(p mysql.Predicate, value int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "menu_id", p),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereMenuIdIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "menu_id", "IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) WhereMenuIdNotIn(value []int64) *umsRoleMenuRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "menu_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsRoleMenuRelationQueryBuilder) OrderByMenuId(asc bool) *umsRoleMenuRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "menu_id "+order)
	return qb
}
