///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package cms_prefrence_area_product_relation

import (
	"fmt"

	"github.com/pkg/errors"
	"gorm.io/gorm"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"
)

func NewModel() *CmsPrefrenceAreaProductRelation {
	return new(CmsPrefrenceAreaProductRelation)
}

func NewQueryBuilder() *cmsPrefrenceAreaProductRelationQueryBuilder {
	return new(cmsPrefrenceAreaProductRelationQueryBuilder)
}

func (t *CmsPrefrenceAreaProductRelation) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type cmsPrefrenceAreaProductRelationQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&CmsPrefrenceAreaProductRelation{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&CmsPrefrenceAreaProductRelation{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&CmsPrefrenceAreaProductRelation{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, nil
	}
	return c, res.Error
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) First(db *gorm.DB) (*CmsPrefrenceAreaProductRelation, error) {
	ret := &CmsPrefrenceAreaProductRelation{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, nil
	}
	return ret, res.Error
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) QueryOne(db *gorm.DB) (*CmsPrefrenceAreaProductRelation, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) QueryAll(db *gorm.DB) ([]*CmsPrefrenceAreaProductRelation, error) {
	var ret []*CmsPrefrenceAreaProductRelation
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) Limit(limit int) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) Offset(offset int) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereId(p mysql.Predicate, value int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereIdIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereIdNotIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) OrderById(asc bool) *cmsPrefrenceAreaProductRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WherePrefrenceAreaId(p mysql.Predicate, value int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "prefrence_area_id", p),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WherePrefrenceAreaIdIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "prefrence_area_id", "IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WherePrefrenceAreaIdNotIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "prefrence_area_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) OrderByPrefrenceAreaId(asc bool) *cmsPrefrenceAreaProductRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "prefrence_area_id "+order)
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereProductId(p mysql.Predicate, value int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", p),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereProductIdIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", "IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) WhereProductIdNotIn(value []int64) *cmsPrefrenceAreaProductRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsPrefrenceAreaProductRelationQueryBuilder) OrderByProductId(asc bool) *cmsPrefrenceAreaProductRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_id "+order)
	return qb
}
