version: '3'
services:
  mall-admin:
    image: mall-go/admin:v1.0
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - ~/mydata/app/mall-admin/logs:/work/logs
      - /etc/localtime:/etc/localtime:ro
    external_links:
      - mysql:mysql
  mall-portal:
    image: mall-go/portal:v1.0
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - ~/mydata/app/mall-portal/logs:/work/logs
      - /etc/localtime:/etc/localtime:ro
    external_links:
      - redis:redis
      - mongo:mongo
      - mysql:mysql
      - rabbitmq:rabbitmq
