///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package sms_flash_promotion

import (
	"fmt"
	"time"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *SmsFlashPromotion {
	return new(SmsFlashPromotion)
}

func NewQueryBuilder() *smsFlashPromotionQueryBuilder {
	return new(smsFlashPromotionQueryBuilder)
}

func (t *SmsFlashPromotion) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type smsFlashPromotionQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *smsFlashPromotionQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *smsFlashPromotionQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&SmsFlashPromotion{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsFlashPromotionQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&SmsFlashPromotion{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsFlashPromotionQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&SmsFlashPromotion{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *smsFlashPromotionQueryBuilder) First(db *gorm.DB) (*SmsFlashPromotion, error) {
	ret := &SmsFlashPromotion{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *smsFlashPromotionQueryBuilder) QueryOne(db *gorm.DB) (*SmsFlashPromotion, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *smsFlashPromotionQueryBuilder) QueryAll(db *gorm.DB) ([]*SmsFlashPromotion, error) {
	var ret []*SmsFlashPromotion
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *smsFlashPromotionQueryBuilder) Limit(limit int) *smsFlashPromotionQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) Offset(offset int) *smsFlashPromotionQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereId(p mysql.Predicate, value int64) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereIdIn(value []int64) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereIdNotIn(value []int64) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderById(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereTitle(p mysql.Predicate, value string) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereTitleIn(value []string) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereTitleNotIn(value []string) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "title", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderByTitle(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "title "+order)
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStartDate(p mysql.Predicate, value time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_date", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStartDateIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_date", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStartDateNotIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_date", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderByStartDate(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "start_date "+order)
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereEndDate(p mysql.Predicate, value time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_date", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereEndDateIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_date", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereEndDateNotIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_date", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderByEndDate(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "end_date "+order)
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStatusIn(value []int32) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereStatusNotIn(value []int32) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderByStatus(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereCreateTime(p mysql.Predicate, value time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereCreateTimeIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) WhereCreateTimeNotIn(value []time.Time) *smsFlashPromotionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionQueryBuilder) OrderByCreateTime(asc bool) *smsFlashPromotionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_time "+order)
	return qb
}
