///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package sms_flash_promotion_session

import (
	"fmt"
	"time"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *SmsFlashPromotionSession {
	return new(SmsFlashPromotionSession)
}

func NewQueryBuilder() *smsFlashPromotionSessionQueryBuilder {
	return new(smsFlashPromotionSessionQueryBuilder)
}

func (t *SmsFlashPromotionSession) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type smsFlashPromotionSessionQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *smsFlashPromotionSessionQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *smsFlashPromotionSessionQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&SmsFlashPromotionSession{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsFlashPromotionSessionQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&SmsFlashPromotionSession{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsFlashPromotionSessionQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&SmsFlashPromotionSession{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *smsFlashPromotionSessionQueryBuilder) First(db *gorm.DB) (*SmsFlashPromotionSession, error) {
	ret := &SmsFlashPromotionSession{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *smsFlashPromotionSessionQueryBuilder) QueryOne(db *gorm.DB) (*SmsFlashPromotionSession, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *smsFlashPromotionSessionQueryBuilder) QueryAll(db *gorm.DB) ([]*SmsFlashPromotionSession, error) {
	var ret []*SmsFlashPromotionSession
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *smsFlashPromotionSessionQueryBuilder) Limit(limit int) *smsFlashPromotionSessionQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) Offset(offset int) *smsFlashPromotionSessionQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereId(p mysql.Predicate, value int64) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereIdIn(value []int64) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereIdNotIn(value []int64) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderById(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereName(p mysql.Predicate, value string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereNameIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereNameNotIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderByName(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStartTime(p mysql.Predicate, value string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_time", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStartTimeIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_time", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStartTimeNotIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "start_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderByStartTime(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "start_time "+order)
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereEndTime(p mysql.Predicate, value string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_time", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereEndTimeIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_time", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereEndTimeNotIn(value []string) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "end_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderByEndTime(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "end_time "+order)
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStatus(p mysql.Predicate, value int32) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStatusIn(value []int32) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereStatusNotIn(value []int32) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderByStatus(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "status "+order)
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereCreateTime(p mysql.Predicate, value time.Time) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", p),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereCreateTimeIn(value []time.Time) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) WhereCreateTimeNotIn(value []time.Time) *smsFlashPromotionSessionQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsFlashPromotionSessionQueryBuilder) OrderByCreateTime(asc bool) *smsFlashPromotionSessionQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_time "+order)
	return qb
}
