///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package sms_home_recommend_product

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *SmsHomeRecommendProduct {
	return new(SmsHomeRecommendProduct)
}

func NewQueryBuilder() *smsHomeRecommendProductQueryBuilder {
	return new(smsHomeRecommendProductQueryBuilder)
}

func (t *SmsHomeRecommendProduct) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type smsHomeRecommendProductQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *smsHomeRecommendProductQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *smsHomeRecommendProductQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&SmsHomeRecommendProduct{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsHomeRecommendProductQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&SmsHomeRecommendProduct{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *smsHomeRecommendProductQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&SmsHomeRecommendProduct{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *smsHomeRecommendProductQueryBuilder) First(db *gorm.DB) (*SmsHomeRecommendProduct, error) {
	ret := &SmsHomeRecommendProduct{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *smsHomeRecommendProductQueryBuilder) QueryOne(db *gorm.DB) (*SmsHomeRecommendProduct, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *smsHomeRecommendProductQueryBuilder) QueryAll(db *gorm.DB) ([]*SmsHomeRecommendProduct, error) {
	var ret []*SmsHomeRecommendProduct
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *smsHomeRecommendProductQueryBuilder) Limit(limit int) *smsHomeRecommendProductQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) Offset(offset int) *smsHomeRecommendProductQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereId(p mysql.Predicate, value int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereIdIn(value []int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereIdNotIn(value []int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) OrderById(asc bool) *smsHomeRecommendProductQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductId(p mysql.Predicate, value int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", p),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductIdIn(value []int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", "IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductIdNotIn(value []int64) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) OrderByProductId(asc bool) *smsHomeRecommendProductQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_id "+order)
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductName(p mysql.Predicate, value string) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_name", p),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductNameIn(value []string) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_name", "IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereProductNameNotIn(value []string) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "product_name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) OrderByProductName(asc bool) *smsHomeRecommendProductQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "product_name "+order)
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereRecommendStatus(p mysql.Predicate, value int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recommend_status", p),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereRecommendStatusIn(value []int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recommend_status", "IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereRecommendStatusNotIn(value []int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "recommend_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) OrderByRecommendStatus(asc bool) *smsHomeRecommendProductQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "recommend_status "+order)
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereSort(p mysql.Predicate, value int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", p),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereSortIn(value []int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) WhereSortNotIn(value []int32) *smsHomeRecommendProductQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "NOT IN"),
		value,
	})
	return qb
}

func (qb *smsHomeRecommendProductQueryBuilder) OrderBySort(asc bool) *smsHomeRecommendProductQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sort "+order)
	return qb
}
