///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_member_rule_setting

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *UmsMemberRuleSetting {
	return new(UmsMemberRuleSetting)
}

func NewQueryBuilder() *umsMemberRuleSettingQueryBuilder {
	return new(umsMemberRuleSettingQueryBuilder)
}

func (t *UmsMemberRuleSetting) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsMemberRuleSettingQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsMemberRuleSettingQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsMemberRuleSettingQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&UmsMemberRuleSetting{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsMemberRuleSettingQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&UmsMemberRuleSetting{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsMemberRuleSettingQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsMemberRuleSetting{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *umsMemberRuleSettingQueryBuilder) First(db *gorm.DB) (*UmsMemberRuleSetting, error) {
	ret := &UmsMemberRuleSetting{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *umsMemberRuleSettingQueryBuilder) QueryOne(db *gorm.DB) (*UmsMemberRuleSetting, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsMemberRuleSettingQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsMemberRuleSetting, error) {
	var ret []*UmsMemberRuleSetting
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsMemberRuleSettingQueryBuilder) Limit(limit int) *umsMemberRuleSettingQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) Offset(offset int) *umsMemberRuleSettingQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereIdIn(value []int64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereIdNotIn(value []int64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderById(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignDay(p mysql.Predicate, value int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_day", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignDayIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_day", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignDayNotIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_day", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByContinueSignDay(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "continue_sign_day "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignPoint(p mysql.Predicate, value int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_point", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignPointIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_point", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereContinueSignPointNotIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "continue_sign_point", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByContinueSignPoint(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "continue_sign_point "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereConsumePerPoint(p mysql.Predicate, value float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "consume_per_point", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereConsumePerPointIn(value []float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "consume_per_point", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereConsumePerPointNotIn(value []float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "consume_per_point", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByConsumePerPoint(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "consume_per_point "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereLowOrderAmount(p mysql.Predicate, value float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "low_order_amount", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereLowOrderAmountIn(value []float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "low_order_amount", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereLowOrderAmountNotIn(value []float64) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "low_order_amount", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByLowOrderAmount(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "low_order_amount "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereMaxPointPerOrder(p mysql.Predicate, value int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_point_per_order", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereMaxPointPerOrderIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_point_per_order", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereMaxPointPerOrderNotIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "max_point_per_order", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByMaxPointPerOrder(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "max_point_per_order "+order)
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereType(p mysql.Predicate, value int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", p),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereTypeIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) WhereTypeNotIn(value []int32) *umsMemberRuleSettingQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberRuleSettingQueryBuilder) OrderByType(asc bool) *umsMemberRuleSettingQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "type "+order)
	return qb
}
