///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package cms_topic_category

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *CmsTopicCategory {
	return new(CmsTopicCategory)
}

func NewQueryBuilder() *cmsTopicCategoryQueryBuilder {
	return new(cmsTopicCategoryQueryBuilder)
}

func (t *CmsTopicCategory) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type cmsTopicCategoryQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *cmsTopicCategoryQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *cmsTopicCategoryQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&CmsTopicCategory{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsTopicCategoryQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&CmsTopicCategory{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsTopicCategoryQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&CmsTopicCategory{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *cmsTopicCategoryQueryBuilder) First(db *gorm.DB) (*CmsTopicCategory, error) {
	ret := &CmsTopicCategory{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *cmsTopicCategoryQueryBuilder) QueryOne(db *gorm.DB) (*CmsTopicCategory, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *cmsTopicCategoryQueryBuilder) QueryAll(db *gorm.DB) ([]*CmsTopicCategory, error) {
	var ret []*CmsTopicCategory
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *cmsTopicCategoryQueryBuilder) Limit(limit int) *cmsTopicCategoryQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) Offset(offset int) *cmsTopicCategoryQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereId(p mysql.Predicate, value int64) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereIdIn(value []int64) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereIdNotIn(value []int64) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderById(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereName(p mysql.Predicate, value string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereNameIn(value []string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereNameNotIn(value []string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderByName(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereIcon(p mysql.Predicate, value string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereIconIn(value []string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereIconNotIn(value []string) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderByIcon(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "icon "+order)
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSubjectCount(p mysql.Predicate, value int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "subject_count", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSubjectCountIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "subject_count", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSubjectCountNotIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "subject_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderBySubjectCount(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "subject_count "+order)
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereShowStatus(p mysql.Predicate, value int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereShowStatusIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereShowStatusNotIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderByShowStatus(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "show_status "+order)
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSort(p mysql.Predicate, value int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", p),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSortIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) WhereSortNotIn(value []int32) *cmsTopicCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsTopicCategoryQueryBuilder) OrderBySort(asc bool) *cmsTopicCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sort "+order)
	return qb
}
