///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_member_member_tag_relation

import (
	"fmt"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *UmsMemberMemberTagRelation {
	return new(UmsMemberMemberTagRelation)
}

func NewQueryBuilder() *umsMemberMemberTagRelationQueryBuilder {
	return new(umsMemberMemberTagRelationQueryBuilder)
}

func (t *UmsMemberMemberTagRelation) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsMemberMemberTagRelationQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsMemberMemberTagRelationQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&UmsMemberMemberTagRelation{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Update(db *gorm.DB, data *UmsMemberMemberTagRelation) (cnt int64, err error) {
	db = db.Model(&UmsMemberMemberTagRelation{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(data)
	err = ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "update err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&UmsMemberMemberTagRelation{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsMemberMemberTagRelation{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *umsMemberMemberTagRelationQueryBuilder) First(db *gorm.DB) (*UmsMemberMemberTagRelation, error) {
	ret := &UmsMemberMemberTagRelation{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *umsMemberMemberTagRelationQueryBuilder) QueryOne(db *gorm.DB) (*UmsMemberMemberTagRelation, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsMemberMemberTagRelationQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsMemberMemberTagRelation, error) {
	var ret []*UmsMemberMemberTagRelation
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Limit(limit int) *umsMemberMemberTagRelationQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) Offset(offset int) *umsMemberMemberTagRelationQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereIdIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereIdNotIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) OrderById(asc bool) *umsMemberMemberTagRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereMemberId(p mysql.Predicate, value int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", p),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereMemberIdIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereMemberIdNotIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) OrderByMemberId(asc bool) *umsMemberMemberTagRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "member_id "+order)
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereTagId(p mysql.Predicate, value int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tag_id", p),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereTagIdIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tag_id", "IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) WhereTagIdNotIn(value []int64) *umsMemberMemberTagRelationQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "tag_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsMemberMemberTagRelationQueryBuilder) OrderByTagId(asc bool) *umsMemberMemberTagRelationQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "tag_id "+order)
	return qb
}
