[hashids]
length = 12
secret = '6ab6122836cfef95f8db'

[language]
local = 'zh-cn'

[mail]
host = 'smtp.163.com'
pass = ''
port = 465
to = ''
user = ''

[mysql]
[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.read]
addr = '47.93.12.26:3306'
name = 'mall'
pass = '1qaz@WSX'
user = 'csz'

[mysql.write]
addr = '47.93.12.26:3306'
name = 'mall'
pass = '1qaz@WSX'
user = 'csz'

[redis]
addr = '47.93.12.26:6379'
db = '0'
maxretries = 3
minidleconns = 5
pass = ''
poolsize = 10
