///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package cms_help_category

import (
	"fmt"

	"github.com/pkg/errors"
	"gorm.io/gorm"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"
)

func NewModel() *CmsHelpCategory {
	return new(CmsHelpCategory)
}

func NewQueryBuilder() *cmsHelpCategoryQueryBuilder {
	return new(cmsHelpCategoryQueryBuilder)
}

func (t *CmsHelpCategory) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type cmsHelpCategoryQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *cmsHelpCategoryQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *cmsHelpCategoryQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&CmsHelpCategory{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsHelpCategoryQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&CmsHelpCategory{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *cmsHelpCategoryQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&CmsHelpCategory{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, nil
	}
	return c, res.Error
}

func (qb *cmsHelpCategoryQueryBuilder) First(db *gorm.DB) (*CmsHelpCategory, error) {
	ret := &CmsHelpCategory{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, nil
	}
	return ret, res.Error
}

func (qb *cmsHelpCategoryQueryBuilder) QueryOne(db *gorm.DB) (*CmsHelpCategory, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *cmsHelpCategoryQueryBuilder) QueryAll(db *gorm.DB) ([]*CmsHelpCategory, error) {
	var ret []*CmsHelpCategory
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *cmsHelpCategoryQueryBuilder) Limit(limit int) *cmsHelpCategoryQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) Offset(offset int) *cmsHelpCategoryQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereId(p mysql.Predicate, value int64) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereIdIn(value []int64) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereIdNotIn(value []int64) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderById(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereName(p mysql.Predicate, value string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereNameIn(value []string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereNameNotIn(value []string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "name", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderByName(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "name "+order)
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereIcon(p mysql.Predicate, value string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereIconIn(value []string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereIconNotIn(value []string) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "icon", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderByIcon(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "icon "+order)
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereHelpCount(p mysql.Predicate, value int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "help_count", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereHelpCountIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "help_count", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereHelpCountNotIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "help_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderByHelpCount(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "help_count "+order)
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereShowStatus(p mysql.Predicate, value int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereShowStatusIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereShowStatusNotIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "show_status", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderByShowStatus(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "show_status "+order)
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereSort(p mysql.Predicate, value int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", p),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereSortIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) WhereSortNotIn(value []int32) *cmsHelpCategoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "sort", "NOT IN"),
		value,
	})
	return qb
}

func (qb *cmsHelpCategoryQueryBuilder) OrderBySort(asc bool) *cmsHelpCategoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "sort "+order)
	return qb
}
