///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package ums_growth_change_history

import (
	"fmt"
	"time"

	"github.com/pkg/errors"
	"gorm.io/gorm"

	"github.com/ChangSZ/mall-go/internal/repository/mysql"
)

func NewModel() *UmsGrowthChangeHistory {
	return new(UmsGrowthChangeHistory)
}

func NewQueryBuilder() *umsGrowthChangeHistoryQueryBuilder {
	return new(umsGrowthChangeHistoryQueryBuilder)
}

func (t *UmsGrowthChangeHistory) Create(db *gorm.DB) (id int64, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type umsGrowthChangeHistoryQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *umsGrowthChangeHistoryQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	if qb.limit != 0 {
		ret = ret.Limit(qb.limit)
	}
	ret = ret.Offset(qb.offset)
	return ret
}

func (qb *umsGrowthChangeHistoryQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (int64, error) {
	db = db.Model(&UmsGrowthChangeHistory{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	ret := db.Updates(m)
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "updates err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsGrowthChangeHistoryQueryBuilder) Delete(db *gorm.DB) (int64, error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	ret := db.Delete(&UmsGrowthChangeHistory{})
	err := ret.Error
	if err != nil {
		return 0, errors.Wrap(err, "delete err")
	}
	return ret.RowsAffected, nil
}

func (qb *umsGrowthChangeHistoryQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&UmsGrowthChangeHistory{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return 0, nil
	}
	return c, res.Error
}

func (qb *umsGrowthChangeHistoryQueryBuilder) First(db *gorm.DB) (*UmsGrowthChangeHistory, error) {
	ret := &UmsGrowthChangeHistory{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		return nil, nil
	}
	return ret, res.Error
}

func (qb *umsGrowthChangeHistoryQueryBuilder) QueryOne(db *gorm.DB) (*UmsGrowthChangeHistory, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *umsGrowthChangeHistoryQueryBuilder) QueryAll(db *gorm.DB) ([]*UmsGrowthChangeHistory, error) {
	var ret []*UmsGrowthChangeHistory
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *umsGrowthChangeHistoryQueryBuilder) Limit(limit int) *umsGrowthChangeHistoryQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) Offset(offset int) *umsGrowthChangeHistoryQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereId(p mysql.Predicate, value int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereIdIn(value []int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereIdNotIn(value []int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderById(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereMemberId(p mysql.Predicate, value int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereMemberIdIn(value []int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereMemberIdNotIn(value []int64) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "member_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByMemberId(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "member_id "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereCreateTime(p mysql.Predicate, value time.Time) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereCreateTimeIn(value []time.Time) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereCreateTimeNotIn(value []time.Time) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_time", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByCreateTime(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_time "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeType(p mysql.Predicate, value int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_type", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeTypeIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_type", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeTypeNotIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByChangeType(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "change_type "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeCount(p mysql.Predicate, value int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_count", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeCountIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_count", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereChangeCountNotIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "change_count", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByChangeCount(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "change_count "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateMan(p mysql.Predicate, value string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_man", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateManIn(value []string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_man", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateManNotIn(value []string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_man", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByOperateMan(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operate_man "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateNote(p mysql.Predicate, value string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_note", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateNoteIn(value []string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_note", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereOperateNoteNotIn(value []string) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "operate_note", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderByOperateNote(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "operate_note "+order)
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereSourceType(p mysql.Predicate, value int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_type", p),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereSourceTypeIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_type", "IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) WhereSourceTypeNotIn(value []int32) *umsGrowthChangeHistoryQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "source_type", "NOT IN"),
		value,
	})
	return qb
}

func (qb *umsGrowthChangeHistoryQueryBuilder) OrderBySourceType(asc bool) *umsGrowthChangeHistoryQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "source_type "+order)
	return qb
}
